# Generated by Django 2.2.26 on 2022-01-23 18:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20220120_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='usercustom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Token',
        ),
    ]
