# Generated by Django 2.2.26 on 2022-01-23 18:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20220123_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='usercustom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
